//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coach_Academy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Club
    {
        public int ID { get; set; }
        public string title { get; set; }
        public string descr { get; set; }
        public string ad { get; set; }
        public Nullable<decimal> rating { get; set; }
        public Nullable<decimal> price { get; set; }
        public byte[] img { get; set; }
    }
}
